###
GET http://localhost:3000/usuarios

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"Hug",
    "senha":"123",
    "email":"hug@gmail.com",
    "telefone":"(48) 9 9999-9999"
}

###

DELETE http://localhost:3000/usuarios/1

###

PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome":"Cuscuz",
    "senha":"123",
    "email":"hug@gmail.com",
    "telefone":"(48) 9 9999-9999",
    "ativo":false
}

### CATEGORIAS

PUT  http://localhost:3000/categoria/1
Content-Type: application/json

{
    "nome":"Doce"
}

###

GET http://localhost:3000/categoria

###

POST http://localhost:3000/categoria
Content-Type: application/json

{
    "nome":"Salgado"
}
