###
GET http://localhost:3000/usuarios?page=2&limit=5

###
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome":"Hug",
    "senha":"123",
    "email":"hug222234@g2443525m32a2il.com",
    "telefone":"(48) 9 9999-9999"
}

###

DELETE http://localhost:3000/usuarios/1

###

PUT http://localhost:3000/usuarios/2
Content-Type: application/json

{
    "nome":"Cuscuz",
    "senha":"123",
    "email":"hug@gmail.com",
    "telefone":"(48) 9 9999-9999",
    "ativo":false
}

### CATEGORIAS

PUT  http://localhost:3000/categoria/1
Content-Type: application/json

{
    "nome":"Doce"
}

###

GET http://localhost:3000/categoria

###

POST http://localhost:3000/categoria
Content-Type: application/json

{
    "nome":"Salgado"
}

###

GET http://localhost:3000/receitas?page=1&limit=10

###

GET http://localhost:3000/receitas?page=2&limit=5

###

POST http://localhost:3000/receitas
Content-Type: application/json

{
  "receita": "Salgado",
  "modo_preparo": "Caça um javali",
  "ingredientes": "blablablab323l32ablablabdwadwadwala",
  "tempo_preparo_minutos": 8766,
  "porcoes": 1,
  "usuario_id": 4,
  "categoria_id": 3
}

